# Generated by Django 4.2 on 2026-04-01 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('login_exitoso', 'Login Exitoso'), ('login_fallido', 'Login Fallido'), ('registro_exitoso', 'Registro Exitoso'), ('acceso_denegado', 'Acceso Denegado'), ('token_refresh', 'Refresh de Token'), ('cuenta_bloqueada', 'Cuenta Bloqueada')], max_length=50)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso',
                'verbose_name_plural': 'Auditorías de Acceso',
                'db_table': 'auditoria_acceso',
            },
        ),
        migrations.CreateModel(
            name='IntentoBloqueado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion_ip', models.GenericIPAddressField(db_index=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('tipo_anomalia', models.CharField(choices=[('multiples_intentos_fallidos', 'Múltiples Intentos Fallidos'), ('ataque_fuerza_bruta', 'Ataque de Fuerza Bruta'), ('patron_sospechoso', 'Patrón Sospechoso')], max_length=50)),
                ('numero_intentos', models.IntegerField(default=1)),
                ('fecha_primer_intento', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_intento', models.DateTimeField(auto_now=True)),
                ('fecha_bloqueo_hasta', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('duracion_bloqueo_segundos', models.IntegerField(default=300)),
                ('razon_bloqueo', models.TextField()),
            ],
            options={
                'verbose_name': 'Intento Bloqueado',
                'verbose_name_plural': 'Intentos Bloqueados',
                'db_table': 'intentos_bloqueados',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario'), ('gerente', 'Gerente')], default='usuario', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('bloqueado', models.BooleanField(default=False)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('razon_bloqueo', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_django', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_autenticacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_access', models.TextField()),
                ('token_refresh', models.TextField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='autenticacion.usuario')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.permiso')),
            ],
            options={
                'verbose_name': 'Rol Permiso',
                'verbose_name_plural': 'Rol Permisos',
                'db_table': 'rol_permisos',
            },
        ),
        migrations.AddIndex(
            model_name='intentobloqueado',
            index=models.Index(fields=['direccion_ip', 'activo'], name='intentos_bl_direcci_e80d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='intentobloqueado',
            index=models.Index(fields=['username', 'activo'], name='intentos_bl_usernam_b836a8_idx'),
        ),
        migrations.AddIndex(
            model_name='intentobloqueado',
            index=models.Index(fields=['fecha_bloqueo_hasta'], name='intentos_bl_fecha_b_7e3e5e_idx'),
        ),
        migrations.AddField(
            model_name='auditoriaacceso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_acceso', to='autenticacion.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AddIndex(
            model_name='auditoriaacceso',
            index=models.Index(fields=['username', 'fecha_evento'], name='auditoria_a_usernam_ec61b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaacceso',
            index=models.Index(fields=['direccion_ip', 'fecha_evento'], name='auditoria_a_direcci_56e202_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaacceso',
            index=models.Index(fields=['tipo_evento', 'fecha_evento'], name='auditoria_a_tipo_ev_9a08f3_idx'),
        ),
    ]
