# Generated by Django 4.2 on 2026-05-03 23:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='IntentoAccesoNoAutorizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_solicitada_id', models.CharField(max_length=100)),
                ('empresa_autorizada_id', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(db_index=True)),
                ('token_identifier', models.CharField(max_length=255)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Intento No Autorizado',
                'verbose_name_plural': 'Intentos No Autorizados',
                'db_table': 'intentos_acceso_no_autorizado',
            },
        ),
        migrations.CreateModel(
            name='RechazoIntegridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion_ip', models.GenericIPAddressField(db_index=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('motivo_rechazo', models.CharField(max_length=500)),
                ('payload_recibido', models.JSONField(default=dict)),
                ('fecha_rechazo', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rechazo Integridad',
                'verbose_name_plural': 'Rechazos Integridad',
                'db_table': 'rechazos_integridad',
            },
        ),
        migrations.AddIndex(
            model_name='rechazointegridad',
            index=models.Index(fields=['direccion_ip', 'fecha_rechazo'], name='rechazos_in_direcci_7c4004_idx'),
        ),
        migrations.AddIndex(
            model_name='rechazointegridad',
            index=models.Index(fields=['endpoint', 'fecha_rechazo'], name='rechazos_in_endpoin_9372a4_idx'),
        ),
        migrations.AddField(
            model_name='intentoaccesonoautorizado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_denegados', to='autenticacion.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='autenticacion.empresa'),
        ),
        migrations.AddIndex(
            model_name='intentoaccesonoautorizado',
            index=models.Index(fields=['usuario', 'fecha_intento'], name='intentos_ac_usuario_65ee1c_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoaccesonoautorizado',
            index=models.Index(fields=['direccion_ip', 'fecha_intento'], name='intentos_ac_direcci_85ffbe_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoaccesonoautorizado',
            index=models.Index(fields=['token_identifier', 'fecha_intento'], name='intentos_ac_token_i_a2cf7f_idx'),
        ),
    ]
