# Generated by Django 4.2.17 on 2026-05-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_merge_0002_auditlog_0002_empresa'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_action_09d227_idx',
            old_name='auditlog_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_ip_addr_f3d5f9_idx',
            old_name='auditlog_ip_address_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_user_id_835db7_idx',
            old_name='auditlog_user_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('suario', 'Usuario'), ('gerente', 'Gerente'), ('manager', 'Manager')], default='usuario', max_length=50),
        ),
    ]
