# Generated by Django 4.2.17 on 2026-05-05 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_django', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Profile',
                'verbose_name_plural': 'Usuario Profiles',
                'db_table': 'usuario_profiles',
            },
        ),
    ]
