# Generated by Django 4.2 on 2026-04-01 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnálisisOptimización',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('tipo_recomendacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ahorro_potencial', models.DecimalField(decimal_places=4, max_digits=15)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analisis_optimizacion',
            },
        ),
        migrations.CreateModel(
            name='ConsumoNube',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('proveedor_nube', models.CharField(choices=[('AWS', 'Amazon Web Services'), ('GCP', 'Google Cloud Platform')], max_length=20)),
                ('cuenta_nube', models.CharField(max_length=255)),
                ('proyecto', models.CharField(db_index=True, max_length=255)),
                ('servicio', models.CharField(choices=[('EC2', 'Elastic Compute Cloud'), ('RDS', 'Relational Database Service'), ('S3', 'Simple Storage Service'), ('Lambda', 'Lambda'), ('DynamoDB', 'DynamoDB')], max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('etiquetas', models.JSONField(default=dict)),
                ('costo_mensual', models.DecimalField(decimal_places=4, max_digits=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consumo de Nube',
                'verbose_name_plural': 'Consumos de Nube',
                'db_table': 'consumo_nube',
            },
        ),
        migrations.CreateModel(
            name='HistorialGeneracionReportes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('tipo_reporte', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_ejecucion_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_generacion_reportes',
            },
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=15)),
                ('costo_aws', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('costo_gcp', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reporte Mensual',
                'verbose_name_plural': 'Reportes Mensuales',
                'db_table': 'reporte_mensual',
            },
        ),
        migrations.CreateModel(
            name='ResumenPorProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=15)),
                ('numero_recursos', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resumen_proyecto',
            },
        ),
        migrations.CreateModel(
            name='TendenciasAnomalias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('tipo_anomalia', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tendencias_anomalias',
            },
        ),
        migrations.AddIndex(
            model_name='consumonube',
            index=models.Index(fields=['empresa_id', 'fecha_registro'], name='consumo_nub_empresa_d2de5e_idx'),
        ),
        migrations.AddIndex(
            model_name='consumonube',
            index=models.Index(fields=['proveedor_nube', 'fecha_registro'], name='consumo_nub_proveed_f3a955_idx'),
        ),
    ]
