# Generated by Django 4.2.17 on 2026-05-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemensual',
            name='empresa_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
