# Generated by Django 4.2.17 on 2026-05-05 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa_models',
            },
        ),
        migrations.CreateModel(
            name='AsociacionUsuarioEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario'), ('gerente', 'Gerente')], default='usuario', max_length=50)),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asociados', to='empresa.empresamodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_asociadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asociación Usuario Empresa',
                'verbose_name_plural': 'Asociaciones Usuario Empresa',
                'db_table': 'asociacion_usuario_empresa',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
